spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/test?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;autoReconnectForPools=true
      username: root
      password:
  redis:
    host: 127.0.0.1
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-test.idc.yst.com.cn:8080/eureka/

# rocketMq 配置信息
rocketMq:
  producer:
    groupName: cos-log-producer
    namesrvAddr: 10.213.3.125:9876
    topic: cos-biz-log
  #    retryTimes: 2
  consumer:
    groupName: cos-log-consumer
    namesrvAddr: 10.213.3.125:9876
    topic: cos-biz-log
#    retryTimes: 3
#    threadMin: 20
#    threadMax: 64
#    messageBatchMaxSize: 1