spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/test?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;autoReconnectForPools=true
      username: root
      password:
  redis:
    host: 127.0.0.1
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-test.idc.yst.com.cn:8080/eureka/
